apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-deployment.yml
- app-service.yml
images:
- name: 241442071922.dkr.ecr.us-west-2.amazonaws.com/test
  newTag: 050b0d805ebe2c4dd78be80afae7cd569c333057
- name: 280389627074.dkr.ecr.us-west-2.amazonaws.com/test
  newTag: 8890d0bd2f4ffa3307b981f36b9b1f683a4eeb35
